#!/bin/sh

set -e
set -x

# Start all necessary processes with Supervisord.
# Stay in foreground unless DAEMONIZE == 1.
if [ $DAEMONIZE == "1" ]; then
	supervisord -c ./targets/run/supervisord.conf
else
	supervisord -c ./targets/run/supervisord.conf -n
fi

exit $?
